
version: "3.3"

services:

  database:
    container_name: dynamodb-local
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
    volumes:
      - ./dynamodb_data:/home/dynamodblocal/data
    ports:
      - "8000:8000"

  app:
    container_name: app
    build: .
    env_file:
      - .env


volumes:
  dynamodb_data: